package tictactoe.model;
// Generated Oct 2, 2014 1:05:43 AM by Hibernate Tools 3.6.0



/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {
    
    private String userName;
    private String firstName;
    private String lastName;
    private String password;
    private int games;
    private int wins;
    private int losses;

    public Player() {
    }

    public Player(String userName, String firstName, String lastName, String password, int games, int wins, int losses) {
       this.userName = userName;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.games = games;
       this.wins = wins;
       this.losses = losses;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public int getGames() {
        return this.games;
    }
    
    public void setGames(int games) {
        this.games = games;
    }
    
    public int getWins() {
        return this.wins;
    }
    
    public void setWins(int wins) {
        this.wins = wins;
    }
    
    public int getLosses() {
        return this.losses;
    }
    
    public void setLosses(int losses) {
        this.losses = losses;
    }

    public int getDraws(){
        return getGames() - (getWins()+getLosses());
    }


}


