package tictactoe.model;
// Generated Oct 2, 2014 1:05:43 AM by Hibernate Tools 3.6.0



/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {
    
    private String userName;
    private int games;
    private int wins;
    private int losses;
    private int draws;

    public Player(String username) {
        this.userName = username;
    }

    public Player(String userName, int games, int wins, int draws, int losses) {
       this.userName = userName;
       this.games = games;
       this.wins = wins;
       this.draws = draws;
       this.losses = losses;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
        
    public int getGames() {
        return this.games;
    }
    
    public void setGames(int games) {
        this.games = games;
    }
    
    public int getWins() {
        return this.wins;
    }
    
    public void setWins(int wins) {
        this.wins = wins;
    }
    
    public int getLosses() {
        return this.losses;
    }
    
    public void setLosses(int losses) {
        this.losses = losses;
    }

    public void setDraws(int draws) {
        this.draws = draws;
    }

    public int getDraws(){
        return draws;
    }
}


